sudo: false
language: node_js
branches:
only:
- master
before_script:
- git config --global user.email "vladocode@gmail.com"
- git config --global user.name "Vlado"
- git remote rm origin
- git remote add origin https://iamvlado:${GH_TOKEN}@github.com/iamvlado/template-for-musician.git
- npm i
script:
- gulp build
after_script:
- gulp deploy
env:
  global:
    secure: iSH/nXWDlFV8mBO5B7Z9BVjdUJsajQC2evR8m0yHqhvF7SfTw/GXu6J3l+k5/qXIJq+YIwYiS1aA9hVUki3jd38RX0dbOMDRseFWx3qRFFZzwzyu/d6UnDJkdH2DwdfOtvFMYRP+742NB4CmB6zDNuz0DYSOWYNZPk8swv2Pk7slDjGZcInPgXPdXPxMnrd2OhbIVGrYS/hGtibIKWivjB3V6jbX6MWWJCGI43hqWhX2rZ8h6lYXQsZPuwAiDvfrz4koOcPSq0OrLOy6ioOpC1OCcIEe5TSt78oBX0zjEn3huMcWlT/cHpzx2END/1VWXwzVwvdmDVtcXRq1N3Fbc9411/bfNtQTJ+TeC4rBi/vEctNFW2rDWCgRjKQ7JzT0mhjeEN32nER4Ezp9snmt310OfpNrzUd5b3WX+q8D0Rb/KZuxB/oJYW1X2iZ8MlICQCS5LdJBXUpjzg6vq9h4c3oSY8eFrwUKSH48U1xkP8ZoLMAQBRN+ekXHTfoeTQ6DmAMfJE+gCuT5cRGhfWHPiDzX14mygDNt7B10LK9zDw2lO29c/xBTQ0Bxh6deU8ew6swfQ9mxJBnkobzQKcePxJYTD3DZm1umGNdyDVhPW/hHRb1Ql9la2bwED95x95LIeEjMY271oP0QS7+iWXN2wir0txuygm+SK97/eU+2EPA=
